### ISSUE TITLE
Can't load backup

### ISSUE THREAD

**Issue by sonqs** [Androz2091/discord-backup#101]
Hello,

So i saved my backup inside a backups folder and drag it over to desktop, and when I wanted to execute the backup, backup id was invalid.

**Comment by sonqs** [comment]
Basically, I have a `json` file with guild backup, ID of backup is: `747926317076447234`, but I get `No backup found`

**Comment by Androz2091** [comment]
Hello @sonqs, indeed if you remove the backup from the storage folder, the code can't find it. Note that you can set your storage folder to desktop.
