### ISSUE TITLE
Somebody stole your code and claimed it as their own

### ISSUE THREAD

**Issue by fantleas** [Androz2091/discord-backup#12]
https://marcloud.net/backupbot/index.html

**Comment by Androz2091** [comment]
Yes, I can see that this person is not respecting the license by not adding copyright, but it doesn't bother me enough to file a complaint. Let him use my package for his bot if he wants, his behavior is not to be praised but what do you want to do about it...
If you want to see more copies of this package, here are some links 😁 

* https://www.npmjs.com/package/discord-backup-bot
* https://www.npmjs.com/package/discord.backup.js
* https://www.npmjs.com/package/dbackup-server

On the other hand, it means that people appreciate....
