### ISSUE TITLE
On Loading A Backup

### ISSUE THREAD

**Issue by PareX2019** [Androz2091/discord-backup#138]
If your trying to load a backup where people have roles in it those roles wont get deleted. so you will have extra roles on the load

**Comment by ayntee** [comment]
This is expected behavior, maybe add an option *overwrite* which will be `true` by default. If the option is `false`, it will first "clear" the guild (delete all the roles, channels, etc. from the guild).

**Comment by PareX2019** [comment]
Alright , thanks, for anyone else reading this (the bot needs to have highest perms in server for this to work)
