### ISSUE TITLE
Channels not backuping?

### ISSUE THREAD

**Issue by MateqB** [Androz2091/discord-backup#14]
I tried the example bot and the channels are not backuping.  Roles and bans are backuping properly. Can you please fix the issue or edit the example bot?

**Comment by MateqB** [comment]
Update: 
Only Text and Voice channels are not loading. Others things backups OK.

**Comment by Androz2091** [comment]
Can you send your code? (the `backup#create()` function)
So categories are loading?

**Comment by MateqB** [comment]
I have exact copy of this: https://www.npmjs.com/package/discord-backup#example-bot

**Comment by MateqB** [comment]
Categories, roles, emojis, bans are loading.

**Comment by MateqB** [comment]
Did you recreated this issue?

**Comment by Androz2091** [comment]
I will try to reproduce it as soon as possible.

**Comment by MateqB** [comment]
I found the issue. When channel has no category then it's not loading. Can you please fix this so channels without category would load too?

**Comment by Androz2091** [comment]
Fix published on npmjs.com. Update the package with `npm install discord-backup@2.0.3`
