### ISSUE TITLE
Loading backup from backupData

### ISSUE THREAD

**Issue by MateqB** [Androz2091/discord-backup#15]
Can you please add function to load an backup from backupData json? This will help in storing backups in databases.

**Comment by Androz2091** [comment]
It already works. You can load a backup using a backupData object like this:
```js
const backup = require('discord-backup');
const backupData = {}; // Your backup data object
backup.load(backupData);
```

**Comment by Androz2091** [comment]
Is this fixing your issue @MateqB?

**Comment by MateqB** [comment]
Yeah, sorry for not responding
