### ISSUE TITLE
Support for discord.js v11?

### ISSUE THREAD

**Issue by INEX07** [Androz2091/discord-backup#16]
Please add support for discord.js v11.

**Comment by RunyardHartley** [comment]
Oh yeah that would be great!

**Comment by Androz2091** [comment]
Will be added

**Comment by RunyardHartley** [comment]
Where is?

**Comment by Androz2091** [comment]
**Will** be added, actually that's not supported

**Comment by RunyardHartley** [comment]
Oh okay

**Comment by Androz2091** [comment]
Support for Discord.js v11 has been added with the `discordjs-v11` branch. You can install it with `npm install Androz2091/discord-backup#discordjs-v11`!

**Comment by RunyardHartley** [comment]
On peut utiliser les fonctions de https://github.com/Androz2091/discord-backup ?

**Comment by Androz2091** [comment]
Yes, it's the same functions.

**Comment by RunyardHartley** [comment]
Problème quand je veux l'installer : `npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-24T12_46_48_848Z-debug.log
root@Runyard:/home/runyard/Sky# npm install Androz2091/discord-backup#discordjs-                                                                             v11
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Androz2091/discor                                                                             d-backup.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-24T12_47_44_483Z-debug.log
`

**Comment by Androz2091** [comment]
@RunyardHartley, see #4

**Comment by RunyardHartley** [comment]
Im sorry but i againt have a error :

**Comment by RunyardHartley** [comment]
Ty!
