### ISSUE TITLE
Gets error when creating backup

### ISSUE THREAD

**Issue by emipa606** [Androz2091/discord-backup#160]
Used the bot-template as is and gets this when running the create command:

```
if (!guild.iconURL()) return [3 /*break*/, 4];
                                           ^
TypeError: guild.iconURL is not a function
    at /home/user/node_modules/discord-backup/lib/index.js:150:44
    at step (/home/user/node_modules/discord-backup/lib/index.js:33:23)
    at Object.next (/home/user/node_modules/discord-backup/lib/index.js:14:53)
    at /home/user/node_modules/discord-backup/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/node_modules/discord-backup/lib/index.js:4:12)
    at /home/user/node_modules/discord-backup/lib/index.js:121:83
    at new Promise (<anonymous>)
    at /home/user/node_modules/discord-backup/lib/index.js:121:35
    at step (/home/user/node_modules/discord-backup/lib/index.js:33:23)

```
Looked at the code but dont really get why it says its not a function when its clearly called as one.

**Comment by Androz2091** [comment]
Hmm, this is weird, are you using discord.js v12? And can you send me your code, even if you used the example?

**Comment by emipa606** [comment]
I see now, I cloned the bot-project from https://github.com/sitepoint-editors/discord-bot-sitepoint
and it seem to have created a local node_modules folder.
I removed that directory so it would use the npm installed version instead.
Ran the create command again and now I dont get any error. 
Took a long while but then I got a success.
Thanks for the quick response!
