### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by DakshNamdev** [Androz2091/discord-backup#165]
Code:
`const fs = require('fs')
 const backup = require('discord-backup')
    if (!fs.existsSync('./BackupX')) {
        fs.mkdirSync('./BackupX', (err) => { 
            if (err) console.log(err)
        });
  backup.setStorageFolder('./BackupX');
    }`
    Load Code: 
`            case 'load':
                try {
                    backup.load(args[1], message.guild, {
                        clearGuildBeforeRestore: config.Settings.clearGuildBeforeRestore
                    }).then(async info => {
                        console.log(info)
                    })
                } catch(e){
                    console.log(e)
                }
            break;`
            
 This gives an error: https://paste.dtechboy.com/ececalaxij.js
 I hope you can help!

Regards, 
Daksh.

**Comment by Androz2091** [comment]
Hello :wave:
You should use:

```js
const fs = require('fs');
const backup = require('discord-backup');

if (!fs.existsSync('./BackupX')) {
	fs.mkdirSync('./BackupX', (err) => {
		if (err) console.log(err)
	});
	backup.setStorageFolder(__dirname+'/BackupX');
}
```

**Load**:
```js
case 'load':
	try {
		backup.load(args[1], message.guild, {
			clearGuildBeforeRestore: config.Settings.clearGuildBeforeRestore
		}).then(async info => {
			console.log(info)
		})
	} catch(e){
		console.log(e)
	}
	break;
```

Let me know if it is working for you
