### ISSUE TITLE
`Only master branch of discord.js library is supported for now. Install it using 'npm install discordjs/discord.js'.`

### ISSUE THREAD

**Issue by goldentg** [Androz2091/discord-backup#17]
`Only master branch of discord.js library is supported for now. Install it using 'npm install discordjs/discord.js'.` error recieved. I am running latest version of discord.js

**Comment by Androz2091** [comment]
Hello,
Can you send a screenshot of `npm list` please?

**Comment by goldentg** [comment]
![image](https://user-images.githubusercontent.com/43283685/74075890-389d1580-49d2-11ea-9c2e-8fd0e32c7b78.png)

**Comment by Androz2091** [comment]
You have to install the master branch of discord.js: `npm i discordjs/discord.js`. Discord.js v11.5.1 is not currently supported.
