### ISSUE TITLE
Add discord.js to depencies

### ISSUE THREAD

**Issue by CodingLappen** [Androz2091/discord-backup#173]
Well it makes no sense to install these seperately.

**Comment by Androz2091** [comment]
It is... already in the dependencies? No?

**Comment by CodingLappen** [comment]
No it wasn't. As I pulled it yesterday and tried to run a script at I got an error message based on that.

**Comment by Androz2091** [comment]
It is. Since Feb 2020. https://github.com/Androz2091/discord-backup/commit/6ee541e52987ed5405bf8676ae72da24957fc6dc
