### ISSUE TITLE
Can i make a purge backup command with this?

### ISSUE THREAD

**Issue by Khaogamermain01** [Androz2091/discord-backup#183]
Title: "**Can i make a purge backup command with this?**"

So can i do it please so give me a code in the comments or if i dont reply go put it on Discord, My discord username is 
Khao_Main#1451

Thank You :)
- Khao

**Comment by Mr-KayJayDee** [comment]
Hello, no you can't with the package but you can do it easily with fs that is a nodejs package. See [How to remove all files from a folder](https://stackoverflow.com/questions/27072866/how-to-remove-all-files-from-directory-without-removing-directory-in-node-js/54903986#:~:text=To%20remove%20all%20files%20from%20a%20directory%2C%20first%20you%20need,unlink%20to%20remove%20each%20file.)

**Comment by Khaogamermain01** [comment]
ok thanks!
