### ISSUE TITLE
Removes things when there are not fields for it in the backup

### ISSUE THREAD

**Issue by tandpfun** [Androz2091/discord-backup#195]
Hi! I was trying out discord-backup to handle templating, so basically backups that wouldn't be deleted and would be accessable to everyone. I didn't want to delete anything in the current server if it wasn't specified in the backup file if not specified in the document, and it works.

For example, I do not want the server icons to be deleted if the server icon value is not specified in the backup save file. As well as emojis.

Is there any way to prevent these from happening, or that this could be added?

Thank you so much!

**Comment by Androz2091** [comment]
Hello,
You can achieve that by handling it yourself. Disable the `clearGuildBeforeRestore` method, and delete the things in the guild (icon, etc.) depending on the content of the backup data. Then, use the load method to apply it to your guild.
