### ISSUE TITLE
Backup end no detected

### ISSUE THREAD

**Issue by Merlode11** [Androz2091/discord-backup#198]
Hello
I recently use the `discord-backup` module to create servers with a template.I choose this function rather than the Discord Templates because I set a function to choose the decoration of my server.
But, I recently create a backup who don't say me when the load of the backup end. And I have to know when the backup end because, the bot create an invite to give me the server.

I only edit this part of the code, in `load.js` :
```js
var loadChannels = function (guild, backupData, options) {
    var loadChannelPromises = [];
    backupData.channels.categories.forEach(function (categoryData) {
        loadChannelPromises.push(new Promise(function (resolve) {
            util_1.loadCategory(categoryData, guild).then(function (createdCategory) {
                categoryData.children.forEach(function (channelData) {
                    channelData.name = channelData.name.includes("%") ? `${options.decos.first}${channelData.name.replace('%', options.decos.end)}` : channelData.name
                    util_1.loadChannel(channelData, guild, createdCategory, options);
                    resolve(true);
                });
            });
        }));
    });
    backupData.channels.others.forEach(function (channelData) {
        channelData.name = channelData.name.includes("%") ? `${options.decos.first}${channelData.name.replace('%', options.decos.end)}` : channelData.name
        loadChannelPromises.push(util_1.loadChannel(channelData, guild, null, options));
    });
    return Promise.all(loadChannelPromises);
};
exports.loadChannels = loadChannels;
```
*I add a line to set the decorations for the channel (``channelData.name = channelData.name.includes("%") ? `${options.decos.first}${channelData.name.replace('%', options.decos.end)}` : channelData.name``)*

So I don't know what's the problem... Can you help me ?

There is the backup file just here :
https://cdn.discordapp.com/attachments/795044906154196992/826753810717343744/games.json

**Comment by Androz2091** [comment]
The best is to edit the json files directly **or**, if you can not because the replacement of channels with decorations is a feature of your bot, you should fork the repository, edit this file https://github.com/Androz2091/discord-backup/blob/master/src/util.ts#L183, build it and publish it on GitHub. You should not edit the javascript files compild by TypeScript. If you need more help, I'm available at https://androz2091.fr/discord.
