### ISSUE TITLE
Error with infos

### ISSUE THREAD

**Issue by RunyardHartley** [Androz2091/discord-backup#22]
Hello,

The backup system works successfully, but the problem arises when I want to load, it always puts me: "Sorry, an error occur ... Please check that I have administrator permissions!" Every time. For he has permission. I searched deeply and found no errors. I simply did a setStorageFolder to store the data in a folder. It saves successfully, but neither load or info works ...

**Comment by Androz2091** [comment]
Hello, can you send your code please?
If you use something like a catch, replace with this:
```js
backup.load(id, backup).then(() => {
}).catch((err) => {
    console.error(err);
    message.channel.send("Sorry, an error...etc");
});
```

**Comment by RunyardHartley** [comment]
Hello, sure!

This is a code (load and infos) : https://pastebin.com/upz3xLC3
This is a error with load : https://i.imgur.com/gRNyHno.png
And error with infos : No backup found

**Comment by Androz2091** [comment]
Are you sure you're using Discord.js `v11.5-dev`? Try to install it using `npm install discordjs/discord.js#11.5-dev`. If you're using Discord.js `v11.5`, it won't break your code.

**Comment by RunyardHartley** [comment]
I'm using 11.5.1, but will it affect my bot if I'm using the dev version?

**Comment by RunyardHartley** [comment]
I'm using 11.5.1, but will it affect my bot if I'm using the dev version?

**Comment by RunyardHartley** [comment]
I install but it's a 11.6-dev not 11.5-dev, it's normal ?

**Comment by Androz2091** [comment]
> I'm using 11.5.1, but will it affect my bot if I'm using the dev version?

No, it won't.

> I install but it's a 11.6-dev not 11.5-dev, it's normal ?

What do you mean? 11.6-dev doesn't exist...

**Comment by RunyardHartley** [comment]
I'm sorry, I test soon

**Comment by RunyardHartley** [comment]
Yay this is work ! But, the 

await message.channel.awaitMessages(m => (m.author.id === message.author.id) && (m.content === "-confirm"), {
                    max: 1,
                    time: 20000,
                    errors: ["time"]

Doesn't not work, It does not wait for me to answer, it starts load directly. And the infos command send me every no backup fond error...

**Comment by Androz2091** [comment]
Hmm... In your `Sky/database/backups` folder, is there a json file named with the backup ID?
Also, you just have to use `setStorageFolder` once, for example in your main file.

**Comment by RunyardHartley** [comment]
Yes it saves with the ID ah and ok, but it does not work yet

**Comment by Dany-LF** [comment]
root@debian:~/flynbot# npm install discordjs/discord.js#11.5-dev
npm ERR! code 1
npm ERR! Command failed: git checkout 11.5-dev
npm ERR! error: pathspec '11.5-dev' did not match any file(s) known to git.
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-29T19_18_21_641Z-debug.log
root@debian:~/flynbot#

This isn't exist mmmh

**Comment by Androz2091** [comment]
@Dany-LF Discord.js released the v11.6, install it using `npm i discord.js`

**Comment by Dany-LF** [comment]
That's great, I didn't know there was an 11.6, I'll go see the changes right now!

**Comment by Dany-LF** [comment]
11.6 and 11.6.1:
"11.6.0 is being released to backport new features from 12.0.0-dev."

(node:23776) UnhandledPromiseRejectionWarning: TypeError: guild.iconURL is not a function

This is weird all my bot work and if i use `npm i discordjs/discord.js` he install v12 but with v12 i can't do anything i think this is an error(i can only use backup with v12)

**Comment by Androz2091** [comment]
You have to use the `discordjs-v11` branch of discord backup.

**Comment by Dany-LF** [comment]
Yeah i see this

**Comment by RunyardHartley** [comment]
Resolved !
