### ISSUE TITLE
Backup codes disappear after a while

### ISSUE THREAD

**Issue by wioniqle-q** [Androz2091/discord-backup#221]
1- After creating a backup, 1-2 days pass and backup codes are lost.
2-When I call the server cleanup function while using the backup load command, some of the channels are not deleted because you have deleted the channels by forEach and the channels are left incorrect with a red mark.
3- Please take channels into for loop and delete them

**Comment by Positive2022** [comment]
` the channels are left incorrect with a red mark.`
what do u mean by red mark?
Maybe the channels are not getting deleted due to ratelimit or permission error?
