### ISSUE TITLE
No delete of categorie/channels/roles...etc after loading a backup

### ISSUE THREAD

**Issue by Pcarlo01** [Androz2091/discord-backup#26]
Hello,
i actually have an issue when i try to load a backup, all the channels in my discord are always here.
So they are not deleted. after that all my backup is importing channel role categories.

I don't have any errors on the console.
i had try with parameter : clearGuildBeforeRestore: true, and without but nothing change

thanks in advance

**Comment by Pcarlo01** [comment]
backup.load("id", message.guild, {
    clearGuildBeforeRestore: true 
});

Work and all the channels have been remove before so it's ok.
Btw i try to add some junk role on the server where i load the backup to see if it delete the roles too.
The roles are still in the server and so the load don't delete the roles.

is there a specific option to add ?

**Comment by Androz2091** [comment]
I updated the package and you don't need to add the `clearGuildBeforeRestore` option. For your other problem, can you check if the highest role of the bot is above the roles that have not been deleted?

**Comment by Pcarlo01** [comment]
indeed, it was the role of the bot that wasn't on the top.
is that possible to make a check if the role is on the top and warn the user if the role is not on the top ?

**Comment by Androz2091** [comment]
You have to check it yourself. You can do it like that:
```js
const allRolesCanBeDeleted = guild.roles.every((r) => r.managed || r.deletable);
```
If your problem is resolved, you can close the issue 😉
