### ISSUE TITLE
TypeError when loading a backup.

### ISSUE THREAD

**Issue by Pixwl** [Androz2091/discord-backup#271]
Hello,

Whenever I try to load my backup, I get the following error:
```
C:\Users\pixwl\Desktop\Projects\Hypervisor\node_modules\discord-backup\lib\util.js:402
                                        if (!(channelData.messages.length > 0)) return [3 /*break*/, 3];
                                                                   ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (C:\Users\pixwl\Desktop\Projects\Hypervisor\node_modules\discord-backup\lib\util.js:402:68)
    at step (C:\Users\pixwl\Desktop\Projects\Hypervisor\node_modules\discord-backup\lib\util.js:33:23)
    at Object.next (C:\Users\pixwl\Desktop\Projects\Hypervisor\node_modules\discord-backup\lib\util.js:14:53)
    at fulfilled (C:\Users\pixwl\Desktop\Projects\Hypervisor\node_modules\discord-backup\lib\util.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Versions:
Discord.js: `13.0.0`
Discord-Backup: `3.0.0`

**Comment by Androz2091** [comment]
Hello,
Can you confirm that the backup was created using Discord Backup v3?
This is pretty weird, because it would mean that somewhere in the backup the messages property of a channel data is undefined. And it should always be at least an empty array. So I guess the problem comes from the creation of the backup... Can you share the json file if there are no personal infos?

**Comment by Pixwl** [comment]
Sure, the JSON file can be found [here](http://hastebin.com/jetegerinu.json)

**Comment by tandpfun** [comment]
I can repro this issue on v3

**Comment by Uthsho** [comment]
I was able to fix this issue on my fork. Xd. Basically the return statement was inside the while loop which meant ChannelData#messages was undefined.

**Comment by Androz2091** [comment]
Indeed this has been fixed thanks to @Uthsho 's PR

**Comment by Uthsho** [comment]
👍👍

**Comment by Androz2091** [comment]
You can install v3.0.1 👌

**Comment by Androz2091** [comment]
Thank you for reporting this issue
and thank you for your PR @Uthsho
