### ISSUE TITLE
ERROR node modules\discord-backup\lib\index.js

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/discord-backup#28]
Waiting for the deError: Cannot find module 'c:\Users\frees\OneDrive\Bureau\futuraself\node_modules\discord-backup\lib\index.js'. Please verify that the package.json has a valid "main" entry

there is the error

**Comment by Androz2091** [comment]
Hello, @sysysysy242 
Can you send your code please?

**Comment by sysysysy242** [comment]
const Discord = require('discord.js');
const client = new Discord.Client();
const backup = require("discord-backup");
const config = require("./config")
client.on('ready', () => {
    console.log(`Connecter entant que ${client.user.tag}!`)
    console.log("--------------------------------------")
    client.user.setActivity(config.status_stream, {
        type: "STREAMING",
        url: "https://www.twitch.tv/ninja"
    });
});




client.on('message', message => {
    let args = message.content.split(" ").slice(1);
if(message.content === config.prefix + "backup create") {
    backup.create(message.guild, {
        jsonBeautify: true
    }).then((backupData) => {
        // And send informations to the backup owner
        message.author.send("The backup has been created! To load it, type this command on the server of your choice: `"+ config.prefix+"load "+backupData.id+"`!");
        message.channel.send(":white_check_mark: Backup successfully created. The backup ID was sent in dm!");
    });
}

if(message.content === config.prefix + "backup load") {
    let backupID = args[0];
    if(!backupID){
        return message.channel.send(":x: | You must specify a valid backup ID!");
    }   

    backup.fetch(backupID).then(async () => {
        // If the backup exists, request for confirmation
        message.channel.send(":warning: | When the backup is loaded, all the channels, roles, etc. will be replaced! Type `-confirm` to confirm!");
            await message.channel.awaitMessages(m => (m.author.id === message.author.id) && (m.content === "-confirm"), {
                max: 1,
                time: 20000,
                errors: ["time"]
            }).catch((err) => {
                // if the author of the commands does not confirm the backup loading
                return message.channel.send(":x: | Time's up! Cancelled backup loading!");
            });
            // When the author of the command has confirmed that he wants to load the backup on his server
            message.author.send(":white_check_mark: | Start loading the backup!");
            // Load the backup
            backup.load(backupID, message.guild).then(() => {
                // When the backup is loaded, delete them from the server
                backup.remove(backupID);
            }).catch((err) => {
                // If an error occurenced
                return message.author.send(":x: | Sorry, an error occurenced... Please check that I have administrator permissions!");
            });
    }).catch((err) => {
        // if the backup wasn't found
        return message.channel.send(":x: | No backup found for `"+backupID+"`!");
    });

}   


if(message.content === config.prefix + "backup info") {
    let backupID = args[0];
    if(!backupID){
        return message.channel.send(":x: | You must specify a valid backup ID!");
    }
    // Fetch the backup
    backup.fetch(backupID).then((backupInfos) => {
        const date = new Date(backupInfos.data.createdTimestamp);
        const yyyy = date.getFullYear().toString(), mm = (date.getMonth()+1).toString(), dd = date.getDate().toString();
        const formatedDate = `${yyyy}/${(mm[1]?mm:"0"+mm[0])}/${(dd[1]?dd:"0"+dd[0])}`;
        let embed = new Discord.MessageEmbed()
            .setAuthor("Backup Informations")
            // Display the backup ID
            .addField("Backup ID", backupInfos.id, false)
            // Displays the server from which this backup comes
            .addField("Server ID", backupInfos.data.guildID, false)
            // Display the size (in mb) of the backup
            .addField("Size", `${backupInfos.size} mb`, false)
            // Display when the backup was created
            .addField("Created at", formatedDate, false)
            .setColor("#FF0000");
        message.channel.send(embed);
    }).catch((err) => {
        // if the backup wasn't found
        return message.channel.send(":x: | No backup found for `"+backupID+"`!");
    });
}

});





client.login(config.token);

**Comment by Androz2091** [comment]
Did you install the package with npm? 🤔

**Comment by sysysysy242** [comment]
no but i this not work
