### ISSUE TITLE
no load backup

### ISSUE THREAD

**Issue by sysysysy242** [Androz2091/discord-backup#29]
I have the code , i create the backups 
And for load this i enter the cmd but this don't work , this not replie a msg 

the script : 

if(message.content === config.prefix + "backup load") {
    let args = message.content.slice("&backup load").trim().split(/ +/g);  
    if(!message.member.hasPermission("ADMINISTRATOR")){
        return message.channel.send(":x: | You must be an administrator of this server to load a backup!");
    }
    let backupID = args[3];        
    if(!backupID){
        return message.channel.send(":x: | You must specify a valid backup ID!");
    }
    // Fetching the backup to know if it exists
    backup.fetch(backupID).then(async () => {
        // If the backup exists, request for confirmation
        backup.load("id", message.guild, {
            clearGuildBeforeRestore: true
            });
    }).catch((err) => {
        // if the backup wasn't found
        return message.channel.send(":x: | No backup found for `"+backupID+"`!");
    });

}

**Comment by Androz2091** [comment]
Yes, that's normal because you're checking if the message content is equal to `&backup load`. If you write `&backup load 982092802` (`982092802` is your backup id), it won't work. You have to use this instead:
```js
if(message.content.startsWith(config.prefix + "backup load")) {
```

**Comment by sysysysy242** [comment]
ty but : (node:1496) UnhandledPromiseRejectionWarning: No backup found

**Comment by Androz2091** [comment]
Here you're trying to load a backup with ID: `"id"`. You have to use `backupID` too.
```js
backup.load(backupID, message.guild, {
clearGuildBeforeRestore: true
});
```
