### ISSUE TITLE
Restoring timestamps

### ISSUE THREAD

**Issue by robertcupisz** [Androz2091/discord-backup#31]
Timestamps don't get restored.

I see that's because the messages are being added to text channels by webhook.send(), so they get the timestamp of when the backup was loaded.

Would be great if the timestamp could be assigned afterwards, but after a quick look through the discord.js api, I don't see an option for that.

Hmm, any ideas? :)

**Comment by Androz2091** [comment]
No, it is impossible to send messages with a different timestamp...

**Comment by robertcupisz** [comment]
Yea, webhook.send() doesn't take that property.

But somehow [Message.createdTimestamp](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=createdTimestamp) is not read-only and can be set. But that seems to only affect the local Message object returned by send(), not the actual message on the server?

**Comment by Androz2091** [comment]
Yes, it's only to edit the local Message object, you can't specify/change a message date.

**Comment by robertcupisz** [comment]
Ah, that's a bummer. Maybe I should open a feature request for Discord. Cheers.
