### ISSUE TITLE
Creating a backup in v12 of DiscordJS

### ISSUE THREAD

**Issue by MackenzieMolloy** [Androz2091/discord-backup#32]
![image](https://user-images.githubusercontent.com/48184419/76109581-a12ce180-5fd4-11ea-88e8-cff8674a6734.png)

Code:
backup.create(message.guild, {
        jsonBeautify: true
    }).then((backupData) => {
      console.log(backupData.id);
    });

**Comment by Androz2091** [comment]
Can you run `npm list` please?

**Comment by MackenzieMolloy** [comment]
> Can you run `npm list` please?

It turns out I wasn't running v12, I was running version 11.6.1

**Comment by Androz2091** [comment]
So you need the discordjs-v11 branch, which is outdated.

**Comment by MackenzieMolloy** [comment]
> So you need the discordjs-v11 branch, which is outdated.
with the v11 branch, I assume? (If so, I'm having issues installing it)

**Comment by Androz2091** [comment]
The 11.x Discord.js version are no longer supported...
