### ISSUE TITLE
Error in creating backup

### ISSUE THREAD

**Issue by tunikakeks** [Androz2091/discord-backup#33]
Error:

(node:25990) UnhandledPromiseRejectionWarning: TypeError: guild.iconURL is not a function
    at /root/node_modules/discord-backup/lib/index.js:147:56
    at step (/root/node_modules/discord-backup/lib/index.js:33:23)
    at Object.next (/root/node_modules/discord-backup/lib/index.js:14:53)
    at /root/node_modules/discord-backup/lib/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/root/node_modules/discord-backup/lib/index.js:4:12)
    at /root/node_modules/discord-backup/lib/index.js:111:79
    at new Promise (<anonymous>)
    at /root/node_modules/discord-backup/lib/index.js:111:31
    at step (/root/node_modules/discord-backup/lib/index.js:33:23)
(node:25990) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:25990) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Androz2091** [comment]
Hello, which version of Discord.js are you using? (run `npm list` if you don't know)

**Comment by MackenzieMolloy** [comment]
I'm having that issue too, I'm running 11.6.1 as 11.5-dev is unavailable

**Comment by Androz2091** [comment]
Discord.js v11.6.1 is not supported. You have to use Discord.js v12 for this package to work.

**Comment by MackenzieMolloy** [comment]
Well... can you fix the 11.5-dev branch
as I cant download it

**Comment by Androz2091** [comment]
It's no longer supported. v11.6 (and 11.5-dev) have become deprecated and it would have taken a long time to continue to maintain them (which I don't have). I recommend that you upgrade to v12 (I understand that this is not always possible for everyone, big changes are indeed to be made).
