### ISSUE TITLE
Images and embeds not being sent

### ISSUE THREAD

**Issue by ChrisvanChip** [Androz2091/discord-backup#34]
Hello :wave:,

It seems images and embeds aren't being backed up while webhooks are capable to send them.

**Comment by Androz2091** [comment]
Good idea, it will be added 👍

**Comment by Androz2091** [comment]
Added. (https://github.com/Androz2091/discord-backup/releases/tag/v2.1.18, https://github.com/Androz2091/discord-backup/releases/tag/v2.1.16)
