### ISSUE TITLE
Issue with backup ID

### ISSUE THREAD

**Issue by ItsHyperOS** [Androz2091/discord-backup#35]
https://sourceb.in/627aec8bac

^^^ Above is my code
When I do `!backup create`, it send me a dm. The backup ID shown is true687285487278358529. Is there any way to get rid of the true? 
Also, just wondering, where does the backup save?  I want to delete it manually, is that possible?
Lastly, is it possible to list all backup ids?

Thanks for making this amazing package!

**Comment by Androz2091** [comment]
Hello,
I'm not able to reproduce the bug. Tested with this code: https://sourceb.in/ed18d3a557.
Discord.js: **v12.0.2**
Discord-backup: **v2.1.13**
![Capture d’écran 2020-03-11 à 16 06 09](https://user-images.githubusercontent.com/42497995/76431930-8e3e5680-63b2-11ea-9d11-3a26e0b4725b.png)

**Comment by ItsHyperOS** [comment]
Hello there, 
I updated the discord-backup and the issue is fixed. Is it possible to manually delete the saves? And is it possible to list all backup Ids?

**Comment by Androz2091** [comment]
Yes, sure. By default, the backups are stored here: `your-project/node_modules/discord-backup/lib/backups`. You can change the storage folder using:
```js
const backup = require("discord-backup");
backup.setStorageFolder(__dirname+"/backups"); // will be saved in ./backups folder
```

To list all the backups, you can use the `backup.list()` method.

**Comment by ItsHyperOS** [comment]
Thank you for your help!

**Comment by baburaomastani** [comment]
bro but when loading the backup which I have to change the file directory so it is not load
