### ISSUE TITLE
Backup fails to create

### ISSUE THREAD

**Issue by dariot99** [Androz2091/discord-backup#38]
Hi, whenever I try to use the b!create command, I get this error in console:

```
(node:19982) UnhandledPromiseRejectionWarning: TypeError: backup.create is not a function
    at Client.<anonymous> (/root/discord-backup/index.js:33:16)
    at Client.emit (events.js:311:20)
    at MessageCreateAction.handle (/root/discord-backup/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/root/discord-backup/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/root/discord-backup/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/root/discord-backup/node_modules/discord.js/src/client/websocket/WebSocketShard.js:435:22)
    at WebSocketShard.onMessage (/root/discord-backup/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/root/discord-backup/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (/root/discord-backup/node_modules/ws/lib/websocket.js:801:20)
(node:19982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Anyone knows what's wrong?

**Comment by dariot99** [comment]
So, I managed to make it work, it makes the backup and sends me the ID via dm, I've tried loading the backup on another server and it backups almost everything (channels, roles, server name and icon) but some categories' channels don't get restored, it just restores the category but no channels in them. Also, when I try to use the b!info or b!fetch commands they don't get me any response

**Comment by Androz2091** [comment]
Hello,
Here are some questions before helping you:
* Do you have any error (when you load the backup **and** when you run the b!infos command)?
* What is your Discord.js version (`npm list`) and your Nodejs version (`node -v`)?
* Can you send me the json file that doesn't work so I can try it on my own computer?

**Comment by dariot99** [comment]
Hi @Androz2091 , first of all thanks for your work and help,

- I'm fairly new to this world, it's the first bot I try to use and self-host, I suppose I have to run it via node index.js to make the bot console start, in fact I get the "I'm ready" message, when I use the b!info or b!fetch commands, nothing happens on console, no errors / warnings, literally nothing. When I load the backup, I get this (consider that the backup still gets actually loaded):

```
(node:5911) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
bitrate: int value should be less than or equal to 96000.
    at RequestHandler.execute (/root/bot/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5911) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- My Discord.js version is: 12.1.1 and Nodejs version is: 12.16.1

- I tried making multiple backups and every of them works the same, restores only the channels of the first category I have, all the other channels of the categories below don't get restored, it just restores the category itself but no channels under that. I just tried making one and restoring it to check if it gave any error message when loading (which happened and I put it above here) and this time it even loaded like 2 times the backup, I had every channel and category doubled (but still no channels restored for the categories below the first one which gets its channels restored normally).
If you want I can try sending you the .json backup files.

Here's a pic from my SSH client: [Imgurl Image](lhttps://i.imgur.com/chqUmyX.png)

I'm fairly sure that I'm missing something or maybe I setup the whole thing in the wrong manner, as I said it's my first bot I try to setup and self-host and I followed some tutorials about the basis.

**Comment by Androz2091** [comment]
Ok, looks like there is a bug with the package for `v12.1.1`... 🤔 
If you can send me your json file, it will help me to fix the issue.

For the b!info/b!fetch commands, that's very weird... Can you send this part of your code please? (the one that handles those commands)

**Comment by dariot99** [comment]
@Androz2091 I'm sending you the json files.
For the b!info command, I was just wrong, it's working fine.

**Comment by Androz2091** [comment]
Oh, I see. Looks like you created the backup on a VIP server (where voice channel bitrate can be up to 128KBps)... and the server on which the backup is restored is not VIP. I will fix this problem.

**Comment by Androz2091** [comment]
It's fixed. I tested to load your backup and it works perfectly. Upgrading discord-backup to v2.1.14 should fix it for you.

**Comment by dariot99** [comment]
Everything works fine now, thanks again for your work @Androz2091 keep up with that!
