### ISSUE TITLE
load Error

### ISSUE THREAD

**Issue by moom08012** [Androz2091/discord-backup#39]
It doesn't automatically turn off after 20,000 seconds...

**Comment by Androz2091** [comment]
Hello @moom08012 
What do you mean?

**Comment by moom08012** [comment]
max: 1,
                    time: 20000,
                    errors: ["time"]
                }).catch((err) => {
                    // if the author of the commands does not confirm the backup loading
                    return message.channel.send(":x: | Time's up! Cancelled backup loading!");

 I can't shut it down.

**Comment by Androz2091** [comment]
I don't understand what's your problem. Can you include screenshots of Discord and of your console, etc...?

**Comment by Androz2091** [comment]
Closed due to inactivity.
