### ISSUE TITLE
Installing discord-backup for discord v11 doesn't work

### ISSUE THREAD

**Issue by Chowcolin** [Androz2091/discord-backup#41]
I'm tryna install discord-backup for djs v11 but when i run 

npm install Androz2091/discord-backup#discordjs-v11

it returns me
```$ npm install Androz2091/discord-backup@discordjs-v11
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Androz2091\discord-backup@discordjs-v11" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Win10SSD1\AppData\Roaming\npm-cache\_logs\2020-04-09T15_58_28_380Z-debug.log```

any help ?

**Comment by Chowcolin** [comment]
Edit: i ran it in a git bash

**Comment by Androz2091** [comment]
Hello,
The version of discord-backup which supported v11 has been deleted, because it was too difficult to maintain it. You will need to use Discord.js v12 to use discord-backup.
