### ISSUE TITLE
max messages ?

### ISSUE THREAD

**Issue by indio0072000** [Androz2091/discord-backup#45]
I have a very active discord. I used your sample bot . The issue I having is it is only saving like 10 messages per channel.

I increased the maxMessagesPerChannel to 1000000 and 100000 and 10000 .  The bot runs , it gets up to 1.5 GB of memory after about 30 minutes and just stop without saving the backup file.

Could you point me in the right direction on how to get a full message backup? Can I adit the code or does it need a rewrite to do it?

**Comment by Androz2091** [comment]
That's weird, it should work. I will look into it as soon as possible 👍

**Comment by indio007** [comment]
It's only fair to let you know there are ALOT of messages on the discord I am trying to back up. I bast guess would be like more than 1 million. Anyhow thx for replying.

**Comment by HeemPlayz** [comment]
It's the best not to backup any messages at all, if restoring pins then it is ok, but 100K message or more than 100 won't help you.

**Comment by Androz2091** [comment]
Yes, indeed I think it is because it needs a lot of requests to Discord, and that you're ratelimited. As I don't think it concerns a lot of users here, I will close the issue. If you really need this, open a new issue
