### ISSUE TITLE
Last Version to support discord.js v11?

### ISSUE THREAD

**Issue by MrDiamond64** [Androz2091/discord-backup#48]
what is the last version for discord-backup that supports discord.js v11?

**Comment by Androz2091** [comment]
@MrDiamond64 No discord-backup version supports discord.js v11...

**Comment by MrDiamond64** [comment]
Is there anyway to use it on v11?

**Comment by Androz2091** [comment]
No (v11 is now a outdated version).

**Comment by Androz2091** [comment]
`discordjs-v11` branch has been restored! Discord.js v11.6 is still outdated, but you can use this branch, which supports v11.6.

**Comment by MrDiamond64** [comment]
But I already updated my whole bot to v12

**Comment by Androz2091** [comment]
So use v12, it's better.
