### ISSUE TITLE
role permissions on text/voice channel

### ISSUE THREAD

**Issue by 0xtokuchi** [Androz2091/discord-backup#52]
I guess it doesn't back them up. This is the biggest problem I have with "backup" ... it would be great if it was added and you can add the system that saves the role and gives them back the role to saved users.

**Comment by Androz2091** [comment]
The role permissions on text and voice channels are restored, yes. For example, if you had a "Staff" role that had access to the #moderators channel, they will have access to the restored server.

**Comment by 0xtokuchi** [comment]
ahh okey, i didnt see that. also its creating bot roles again and as you
know bot roles are not deleted, so copy those roles and open them again. so
there are two roles each. you better fix it. I can take pictures if you
want.

8 May 2020 Cum 18:05 tarihinde Androz <notifications@github.com> şunu yazdı:

**Comment by Androz2091** [comment]
Yes, I see. This will be fixed in the next version!

You can open a PR if you know how to fix it (I think we should add a filter to check if the role is managed here: https://github.com/Androz2091/discord-backup/blob/master/src/master/create.ts#L39)

**Comment by 0xtokuchi** [comment]
.filter(!<role>.managed && <guild.me>roles.highest.comparePositionTo(<role>) > 0) its will be work i think thanks.

**Comment by Androz2091** [comment]
I don't think checking permissions is really a good idea. I think we want to have a full backup, not depending on the permissions of the bot that made it.

**Comment by 0xtokuchi** [comment]
aw sorry, i didnt say that. opens them for the second time because they cannot delete the high roles from the bot and the highest role of the bot

**Comment by Androz2091** [comment]
Yes, but in this part of the code, it is not the deletion of roles, but their backup. And you don't have to be above the role to get information about it.

**Comment by 0xtokuchi** [comment]
yupp but for example eyo is the highest role in guild you can look to picture
![Screenshot_20200508-183205_Discord](https://user-images.githubusercontent.com/65005379/81421561-51949e80-915a-11ea-8404-498e0af724c2.jpg)

**Comment by 0xtokuchi** [comment]
also it doesn't write the permissions of some roles on channels after another try (I have defined 5 role permissions to the channel but 3 of them have been rewritten) I have an idea about this subject, I would like to tell if you are interested

**Comment by Androz2091** [comment]
Fixed in v2.1.17.

**Comment by misa-coder** [comment]
Permissions are not completely fetch with older version in my case too. Idk about V2.1.17

**Comment by Androz2091** [comment]
Please open a new issue if you still have the problem with more details
