### ISSUE TITLE
Storage Folder Problem

### ISSUE THREAD

**Issue by HeemPlayz** [Androz2091/discord-backup#67]
Hey

I made a backup code using your package
I set a storage folder for it but I always get this error
```(node:21113) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/backups'
```
I made a folder called backup to store the data in, any solutions?
I use glitch host, should I use my PC or a Linux, which are better?

**Comment by Androz2091** [comment]
Hello,
You should use that:
```js
backup.setStorageFolder(__dirname+"/backups/"); 
// __dirname will use your current folder
```
instead of `/backups` (/ means the root folder, and you don't have the permissions to write here on glitch).

**Comment by HeemPlayz** [comment]
Backup files aren't shown until I refresh the project on glitch, so it won't save, is it possible to save in JSON file or any Database?

**Comment by Androz2091** [comment]
Yes, sure. Use:
```js
const backups = require("./backups.json");

const fs = require("fs");
const backup = require("discord-backup");

backup.create(guild, {
    jsonSave: false
}).then((backupData) => {
    backups.push(backupData);
    fs.writeFileSync("./backups.json", JSON.stringify(backups));
});
```
and all your backups will be stored in the same file.

**Comment by HeemPlayz** [comment]
Thanks, and I was wondering, if we like can change what the backup id includes, example: numbers, letters and marks
and when we request list(), if it just gives the author his backups only

**Comment by HeemPlayz** [comment]
and why jsonSave: false?

**Comment by Androz2091** [comment]
> Thanks, and I was wondering, if we like can change what the backup id includes, example: numbers, letters and marks

At this time, this is not possible. But you can save your files yourself.

> and when we request list(), if it just gives the author his backups only

You need to make your own database (with json files for example), to store additional data like the ID of the author.

> and why jsonSave: false?

When this is specified, `discord-backup` won't save the backup in the storage folder. This means that it will be up to you, once you have retrieved the backup data (the `backupData` object), to save the backup in your own database.
