### ISSUE TITLE
automatically errors out

### ISSUE THREAD

**Issue by sambeano7** [Androz2091/discord-backup#90]
when I load a backup it automatically errors out saying it doesn't have admin perms in the server yet it does have perms...also is it possible to make it take a few seconds so it doesn't just nuke the server and then not work?

**Comment by sambeano7** [comment]
this is the error in the console ```js
TypeError: guild.setWidget is not a function```

**Comment by Androz2091** [comment]
Hello, this is because you're not using the latest version of Discord.js. Use `npm install discord.js@latest` and it will work.

**Comment by sambeano7** [comment]
I'm 100% positive it's the latest version

**Comment by sambeano7** [comment]
itn worked after I changed the json save to true...thanks though

**Comment by Androz2091** [comment]
This is weird, and it seems impossible... But it's perfect if it's working for you
