### ISSUE TITLE
Different id setup

### ISSUE THREAD

**Issue by sambeano7** [Androz2091/discord-backup#95]
Is there a way to shorten the id? or atleast make it something like 8 characters long with a mixture of numbers and letters? I looked through the code and didn't see anything that caught my eye.

**Comment by Androz2091** [comment]
You can by editing the code, but I will make a function to make it customizable.

**Comment by sambeano7** [comment]
That's fine if you don't but I just don't see it in the code anywhere that would need changed.

**Comment by sambeano7** [comment]
I believe I found it in the index.js file...is this the line that creates the backup code?
```id: SnowflakeUtil.generate(Date.now())```

**Comment by Androz2091** [comment]
Yes, that's it.
